server:
  port: 9090

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/kindergardendb?serverTimezone=UTC&useSSL=false
    username: root
    password: Allen8731!
#    mysql 5.8과 8버전의 드라이버 이름이 다름
#    5.8은 com.mysql.jdbc.Driver
#    8은 com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
##      thymeleaf 사용하기위해서는 security config가 따로 필요함
##      그냥 놔두면 WEB-INF가 없어서 role,접근제어등이 안됨
##      servlet을 사용하지 않는거니까
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5